name: "workflow langue"
on: 
  push: 
    branches : 
      - lang
jobs:
  fr-job:
    if : ${{LANG == 'FR'}}
    runs-on: ubuntu-latest
    steps:
      - name: Afficher un message
        run: echo "L'utilisateur ${{githup.actor}} parle fran√ßais"

      
  second-job:
    if : ${{LANG != 'FR'}}
    runs-on: macos-latest
    steps:
      - name: Afficher un message
        run: echo "user ${{githup.actor}} speaks english"
